# 面板api服务配置

# 服务端口
port: 5333

# 调试模式
debug: false

# wormhole代理
wormhole:
  # 启动代理
  enable: false
  # 代理服务器,例：ws://localhost:3000/ws/
  server:
  # 客户端id,数字+字母，确保唯一性
  clientId:

# token的secretKey，请不要手动修改
secretKey:
